//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        [DisplayName("ID")]
        [Required]
        public string id { get; set; }
        [Required]
        [DisplayName("Fullname")]
        public string fullname { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{dd-MM-YYY}", ApplyFormatInEditMode = true)]
        [DisplayName("Birthday")]
        public System.DateTime birthday { get; set; }
        [Required]
        [DisplayName("Gender")]
        public bool gender { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [DisplayName("Email")]
        public string email { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Phone")]
        public string phone { get; set; }
        [Required]
        [DisplayName("Address")]
        public string address { get; set; }
    }
}
